### Pandas
pandas a python library that is extensively used for data analytics, ML and other Data fields  
It provides possibility to organise data into something called Dataframe, which acts as a table of data (2D)  
It is organised into rows and columns with named indices

In [2]:
import pandas as pd

In [3]:
# Create a data frame using the pandas function
DF = pd.DataFrame ({
                    'Name' : ['Vishnu', "Ram", 'Bharat'], 
                    'Id' : [234, 201, 78],
                    'Course' : ['ML', 'GenAI', "Python"],
                    'Batch' : ['C1', 'C2', 'C1']})
DF

     Name   Id  Course Batch
0  Vishnu  234      ML    C1
1     Ram  201   GenAI    C2
2  Bharat   78  Python    C1

In [4]:
# Let us understand how is it organised
print ("Data type : \n", DF.dtypes)

print ("Index : \n", DF.index)

print ("Number of Records : \n", len(DF))

print ("Number of Fields : \n", len(DF.columns))

Data type :
 Name        str
Id        int64
Course      str
Batch       str
dtype: object
Index :
 RangeIndex(start=0, stop=3, step=1)
Number of Records :
 3
Number of Fields :
 4

In [6]:
# Access specific Column
Names = DF['Name']

print ("Type : \n", type (Names))
print ("Content : \n",  Names)

Type :
 <class 'pandas.Series'>
Content :
 0    Vishnu
1       Ram
2    Bharat
Name: Name, dtype: str

In [7]:
# Access specific Row
Rec_1 = DF.iloc [1] # Access a row based on the index position

print ("Type : \n", type (Rec_1))
print ("Content : \n",  Rec_1)

Type :
 <class 'pandas.Series'>
Content :
 Name        Ram
Id          201
Course    GenAI
Batch        C2
Name: 1, dtype: object

In [8]:
# Make specific Column in a data frame
Names = DF[['Name']]

print ("Type : \n", type (Names))
print ("Content : \n",  Names)

Type :
 <class 'pandas.DataFrame'>
Content :
      Name
0  Vishnu
1     Ram
2  Bharat

In [9]:
# Filter out rows based on condition
Filtered = DF[DF['Batch'] == 'C1']
Filtered

     Name   Id  Course Batch
0  Vishnu  234      ML    C1
2  Bharat   78  Python    C1

In [ ]:
# Update an exising column values : just an assignment
DF['Id'] = [145, 156, 88]
DF

In [ ]:
# Add another column, again just like a variable assignment
DF ['Score'] = [78, 85, 80]
DF

In [10]:
# Add Rows by concatenating
new_rec = pd.DataFrame ({
                        'Name' : ['Dileep', 'Phani'],
                        'Id' : [101, 102],
                        'Course' : ['GenAI', 'ML'],
                        'Batch' : ['C1', 'C2'],
                        'Score' : [80, 75]
})
new_rec

     Name   Id Course Batch  Score
0  Dileep  101  GenAI    C1     80
1   Phani  102     ML    C2     75

In [ ]:
DF = pd.concat ([DF, new_rec], ignore_index=True)
DF

In [ ]:
# Aggregating functions. See how the column is accessed
print ("Min Score : ", DF.Score.min())
print ("Max Score : ", DF.Score.max())
print ("Mean Score : ", DF.Score.mean())
print ("Median Score : ", DF.Score.median())

In [ ]:
# Check the Max score per course : Use Group by
grp = DF.groupby ('Course') ['Score'].max ().rename ("Max ")
grp

In [ ]:
# Read Data from CSV file
Rain_Data = pd.read_csv ('RainFall.csv')
print (Rain_Data.dtypes)
print (len(Rain_Data))

In [ ]:
# Filter the rows for annual rain fall higher than 1500
Rainy_Area = Rain_Data[Rain_Data['ANNUAL'] >= 1500]
Rainy_Area

In [ ]:
# Check Statistical summary of fields
print (Rain_Data[['ANNUAL', 'JAN', 'FEB', 'MAR']].describe())

In [ ]:
# Check Region Wise average
Summary = Rain_Data.groupby ('SUBDIVISION')['ANNUAL'].mean ().rename ("Annual Average").reset_index ()
Summary

In [ ]:
# Check min, max and average per region
summary = Rain_Data.groupby("SUBDIVISION")["ANNUAL"].agg(annual_min="min",annual_max="max",annual_avg="mean").reset_index()
summary

In [ ]:
# Filter the years where each sub division had annual rainfall above its average
filtered = Rain_Data[
    Rain_Data["ANNUAL"] >
    Rain_Data.groupby("SUBDIVISION")["ANNUAL"].transform("mean")
]
filtered

In [ ]:
# Make Quarter wise average
Rain_Data["Q1_avg"] = Rain_Data[["JAN", "FEB", "MAR"]].mean(axis=1)
Rain_Data["Q2_avg"] = Rain_Data[["APR", "MAY", "JUN"]].mean(axis=1)
Rain_Data["Q3_avg"] = Rain_Data[["JUL", "AUG", "SEP"]].mean(axis=1)
Rain_Data["Q4_avg"] = Rain_Data[["OCT", "NOV", "DEC"]].mean(axis=1)
Rain_Data